[general]
import = [
    "~/.config/alacritty/themes/themes/tokyonight.toml"
]

[env] 
TERM = "xterm-256color"

[window]
option_as_alt = "Both"

[font]
size = 10.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
