[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env] 
TERM = "xterm-256color"

[window]
option_as_alt = "Both"

[font]
size = 10.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
